// task actions
export const ADD_TASK_MESSAGES = 'ADD_TASK_MESSAGES';
export const REMOVE_TASK_MESSAGES = 'REMOVE_TASK_MESSAGES';
export const TASK_LIST_LOADED = 'TASK_LIST_LOADED';
export const REMOVE_TASK_MESSAGE = 'REMOVE_TASK_MESSAGE';

// authentication actions
export const UPDATE_AUTHENTICATION_STATUS = 'UPDATE_AUTHENTICATION_STATUS';
export const ADD_AUTHENTICATION_MESSAGE = 'ADD_AUTHENTICATION_MESSAGE';
export const REMOVE_AUTHENTICATION_MESSAGE = 'REMOVE_AUTHENTICATION_MESSAGE';
