
spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/oauth
    username: root
    password: v@l3nsdatalabs
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
server:
  port: 8081
